### ISSUE TITLE
你好，有个疑问

### ISSUE THREAD

**Issue by Jsonjia** [Quyunshuo/AndroidBaseFrameMVVM#1]
看到你的项目，感觉写的很棒，从中有个疑问就是，你的BaseViewModel类一直没有被用到，下载你的demo看了也没有用到，所以想问下，用BaseViewmodel注意什么，有参考的demo吗

**Comment by Quyunshuo** [comment]
你好，你的问题我已了解，项目中`BaseViewModel`类是有被使用到的，项目有两个分支，`master`分支是框架，`demo`分支是我写的一个demo，在`Lib_Translation`Module中，`TranslationActivity`的ViewModel类(`TranslationViewModel`)是继承自`BaseViewModel`的。  
`BaseViewModel`主要是想封装一些公共代码和对Respostory层进行初始化，比如里面我写了两个LiveData，一个是是否加载Loading的LiveData，一个是请求异常的LiveData，子类可以订阅需要的LiveData，比如我加载了一个网络请求，我需要显示Loading图，我就可以在发起请求是改变该LiveData的值，在View层做出一些操作。在`TranslationActivity`类中有示例。demo中的`BaseViewModel`知识针对于demo写了两个都会使用到的LiveData，真正的项目中可以根据实际情况进行封装。这个框架也是比较简单的，如果还有后续的问题，可以在联系。

**Comment by Jsonjia** [comment]
> 你好，你的问题我已了解，项目中`BaseViewModel`类是有被使用到的，项目有两个分支，`master`分支是框架，`demo`分支是我写的一个demo，在`Lib_Translation`Module中，`TranslationActivity`的ViewModel类(`TranslationViewModel`)是继承自`BaseViewModel`的。
> `BaseViewModel`主要是想封装一些公共代码和对Respostory层进行初始化，比如里面我写了两个LiveData，一个是是否加载Loading的LiveData，一个是请求异常的LiveData，子类可以订阅需要的LiveData，比如我加载了一个网络请求，我需要显示Loading图，我就可以在发起请求是改变该LiveData的值，在View层做出一些操作。在`TranslationActivity`类中有示例。demo中的`BaseViewModel`知识针对于demo写了两个都会使用到的LiveData，真正的项目中可以根据实际情况进行封装。这个框架也是比较简单的，如果还有后续的问题，可以在联系。

是我下载分支搞错了，我明明下载的是demo分支，结果不小心下成了master分支，很感谢你的回复，给你点赞

**Comment by Quyunshuo** [comment]
> > 你好，你的问题我已了解，项目中`BaseViewModel`类是有被使用到的，项目有两个分支，`master`分支是框架，`demo`分支是我写的一个demo，在`Lib_Translation`Module中，`TranslationActivity`的ViewModel类(`TranslationViewModel`)是继承自`BaseViewModel`的。
> > `BaseViewModel`主要是想封装一些公共代码和对Respostory层进行初始化，比如里面我写了两个LiveData，一个是是否加载Loading的LiveData，一个是请求异常的LiveData，子类可以订阅需要的LiveData，比如我加载了一个网络请求，我需要显示Loading图，我就可以在发起请求是改变该LiveData的值，在View层做出一些操作。在`TranslationActivity`类中有示例。demo中的`BaseViewModel`知识针对于demo写了两个都会使用到的LiveData，真正的项目中可以根据实际情况进行封装。这个框架也是比较简单的，如果还有后续的问题，可以在联系。
> 
> 是我下载分支搞错了，我明明下载的是demo分支，结果不小心下成了master分支，很感谢你的回复，给你点赞

谢谢支持
