### ISSUE TITLE
Hilt非App模式（单模块）启动时的使用问题

### ISSUE THREAD

**Issue by chesonsir** [Quyunshuo/AndroidBaseFrameMVVM#10]
最新增加的Hilt依赖注入，作者是在主模块（app模块）的AppApplication上添加@HiltAndroidApp，这样的话子模块（例如module_home）在作为单独app启动时就没有Application作为入口，就会报错，官方说的是Hilt不能只在某一个子模块中启动，例如A依赖B，在A中启动Hilt，可以找到B中的依赖注入内容，如果在B中启动Hilt，则找不到A中的依赖内容，所以我是在每个子模块中添加了单独的Application，继承自BaseApplication，作为Hilt的入口，例如
```kotlin
@HiltAndroidApp
class ModuleHomeApplication : BaseApplication() 
```
再在子模块作为app启动时的AndroidManifest中指定启动的Application，建议作者考虑一下相关内容，谢谢

**Comment by Quyunshuo** [comment]
你说的是正确的，只不过这部分逻辑我没有写出来，这部分是需要加在demo里的，只不过我还没有抽出时间来写demo

**Comment by chesonsir** [comment]
还有就是EventBus注册和解除注册时是不是加一个
```kotlin
EventBus.getDefault().isRegistered(subscriber)
```
判断一下好一点

**Comment by Quyunshuo** [comment]
你可以具体说一下为什么要加这个判断的考虑吗？

**Comment by chesonsir** [comment]
我是结合Navigation使用，Fragment在跳转会报EventBus重复注册这个错误

**Comment by Quyunshuo** [comment]
Navigation我没有用过，了解过一些，刚刚我去百度了一下，在启动另一个fragment 时，上一个应该是会被销毁掉的，所以会不会是没有及时取消注册eventBus你才出现了那种情况。目前不用Navigation的情况下是没有问题的，而且如果以后框架上要支持Navigation的话，我也会全面的去优化的。

**Comment by chesonsir** [comment]
BaseFrameFragment解绑是放在onDestroy里，我试了一下放在onStop里好像也不行，EventBus还会内存泄漏

**Comment by Quyunshuo** [comment]
你说的是结合Navigation使用吗

**Comment by chesonsir** [comment]
是的

**Comment by Quyunshuo** [comment]
因为我没有深入使用过Navigation，并且框架也没有对Navigation进行支持，所以你的问题我可能暂时解答不了，但是我觉得可以从Navigation启动或者返回退栈fragment时的生命周期状态，进行注册和解除注册的处理，希望可以帮到你

**Comment by chesonsir** [comment]
好的
