### ISSUE TITLE
大佬能不能出个详细的文档？

### ISSUE THREAD

**Issue by lexluthors** [Quyunshuo/AndroidBaseFrameMVVM#11]
能不能出个详细的使用文档？

**Comment by Quyunshuo** [comment]
详细的是指哪些地方详细？
说实话我现在有点懒🤣

**Comment by lexluthors** [comment]
@Quyunshuo 就是一个详细的使用文档。各个模块怎么独立调试，怎么合并调试等等。

**Comment by Quyunshuo** [comment]
这些都是组件化的基本操作了，和框架没有太大的关系，都是通过一个字段来控制是单独运行还是作为组件被app依赖，单独调试一般情况下需要单独写一个逻辑，代码都会放在一个特定的包内，正式环境会把这个包的内容排除掉

**Comment by Quyunshuo** [comment]
你找一下组件化的教程 都会有这方面的教程的

**Comment by Quyunshuo** [comment]
我已经在开发一个完整项目作为该框架的示例项目，由于工作较忙，可能需要一段时间，项目地址我已经更新在该仓库关于demo的那一段里了，可以关注下进度，对于这个框架，我觉得更需要的是一个比较完整的示例项目。

**Comment by lexluthors** [comment]
感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月26日(周一) 凌晨0:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Quyunshuo/AndroidBaseFrameMVVM] 大佬能不能出个详细的文档？ (#11)




 
我已经在开发一个完整项目作为该框架的示例项目，由于工作较忙，可能需要一段时间，项目地址我已经更新在该仓库关于demo的那一段里了，可以关注下进度，对于这个框架，我觉得更需要的是一个比较完整的示例项目。
