### ISSUE TITLE
使用模块运行模式时依赖HiltAndroidApp

### ISSUE THREAD

**Issue by Wingge** [Quyunshuo/AndroidBaseFrameMVVM#13]
使用app运行时因为有AppApplication的HiltAndroidApp注解可以运行没有问题。
但，isAppMode改为true，运行模块时比如module_home，就会报Hilt异常：没有HiltAndroidApp声明！

**Comment by Quyunshuo** [comment]
组件单独运行时你需要给当前运行的组件一个自定义的Applocation，并且需要添加这个注解，表示该Applocation是注入入口

**Comment by Quyunshuo** [comment]
> 使用app运行时因为有AppApplication的HiltAndroidApp注解可以运行没有问题。
> 
> 但，isAppMode改为true，运行模块时比如module_home，就会报Hilt异常：没有HiltAndroidApp声明！

组件单独运行时你需要给当前运行的组件一个自定义的Applocation，并且需要添加这个注解，表示该Applocation是注入入口

**Comment by Quyunshuo** [comment]
我应该是没有写单独运行的逻辑，因为home模块只是一个为了测试用的，想着后期写demo时把整体逻辑写上。

**Comment by Wingge** [comment]
> > 使用app运行时因为有AppApplication的HiltAndroidApp注解可以运行没有问题。
> > 但，isAppMode改为true，运行模块时比如module_home，就会报Hilt异常：没有HiltAndroidApp声明！
> 
> 组件单独运行时你需要给当前运行的组件一个自定义的Applocation，并且需要添加这个注解，表示该Applocation是注入入口

HiltAndroidApp注解只能有一个的，自定义的Applocation也加上会有编译错误！
