### ISSUE TITLE
关于kotlin方法注释无法自动生成params 和 return

### ISSUE THREAD

**Issue by sweet2o09** [Quyunshuo/AndroidBaseFrameMVVM#14]
你好,为什么我的kotlin在方法注释上不会自动生成@param context Context 这一项 是需要设置的么?
![image](https://user-images.githubusercontent.com/8555893/128134995-f2004b8c-a4da-4c3a-a4ab-47b7b0c4707f.png)

**Comment by Quyunshuo** [comment]
你下载一个插件就可以了，插件名是：BugKotlinDocument，在AS的插件市场能搜到
