### ISSUE TITLE
发起请求的域名放哪里呢

### ISSUE THREAD

**Issue by dewi23** [Quyunshuo/AndroidBaseFrameMVVM#18]
请求的封装是在哪个模块下啊

**Comment by Quyunshuo** [comment]
> 请求的封装是在哪个模块下啊

NetBaseUrlConstant 这个类里面

**Comment by Quyunshuo** [comment]
> 网络请求的模块 module没有吗？

没有做示例模块，不过你可以看我的未完成的玩安卓项目，[WanAndroidMVVM](https://github.com/Quyunshuo/WanAndroidMVVM)，这个项目里有网络请求和简单的功能
