### ISSUE TITLE
如果返回结果包含泛型

### ISSUE THREAD

**Issue by chenmingyin** [Quyunshuo/AndroidBaseFrameMVVM#2]
如题！
我的返回结果类似于{"code":"200", "msg":"xxx","data": T}这种格式，T是泛型，现在使用gson的话，会出现泛型擦除,T会被解析成LinkedTreeMap,报错java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to xxx.
请问大佬有没有什么比较好的解决办法？

**Comment by Quyunshuo** [comment]
能上段代码吗？

**Comment by chenmingyin** [comment]
ApiService接口里这样
`@POST("user")
    suspend fun <T> getUserManage(
        @Body
        result: RequestBody
    ): ResponseResult<T>`

ResponseResult是返回结果的数据类
`data class ResponseResult<T> (
    val resultCode: Int,
    val message: String,
    val result: T
)`
因为返回数据里只有result字段里的数据不同，我就想把它弄成一个泛型，结果默认的gson的ConverterFactory可能解析有问题，不能把泛型解析成javaBean。
`Retrofit.Builder()
            .client(okHttpClient)
            .baseUrl(NetworkUrl.BASE_HOST)
            .addConverterFactory(GsonConverterFactory.create())
            .build()`
我现在看到网上好像说要自定义GsonConverterFactory，想问大佬有没有什么解决办法

**Comment by Quyunshuo** [comment]
你应该是想把公共部分抽离出来，我可以给你看下我是怎么写的，你看下是否可以解决你的问题
我写了一个返回数据的基类，和你结构一致是{"code":"", "msg":"","data": T}这种类型的
```
data class BaseResponse<D>(
    val code: Int,
    val `data`: D,
    val msg: String
)
```
这个数据类的data是泛型，在使用时是这样的  比如我有一个{"code":"200", "msg":"xxx","data": ["a","b"]}这种格式的数据，在ApiService接口可以这样定义
```
@GET("padVersion?")
suspend fun getTestData(@Query("version") versionCode: Int): BaseResponse<List<String>>
```
我在项目中是这么写的

**Comment by chenmingyin** [comment]
我的项目里是共用一个接口，通过传入不同的请求参数获得不同的返回数据，所以我在ApiService里面只写了一个函数。
`suspend fun <T> getUserInfo(
        @Body
        result: RequestBody
    ): ResponseResult<T>`
当在Repositiory中调用时，如NetworkRequest.userManageService.getUserInfo<UserBean>()这样调用时，返回值ResponseResult里好像获取不到UserBean，我刚学kotlin没多久，不知道是不是我的泛型函数写的有问题。
像你上面这种写法可以正确运行，但是对我这个只有一个接口的项目来说，需要写很多函数才行。
我现在不知道这个泛型函数应该怎么写？求大佬指点！

**Comment by Quyunshuo** [comment]
我没有办法，似乎你的思路行不通，你以前用Java的时候，这种方式不会异常吗

**Comment by chenmingyin** [comment]
好像是的，我在网上查到好像是通过内联函数来做的，看来暂时只能通过写多个函数来解决了。
谢谢你的回复。
