### ISSUE TITLE
initRequestData可以在baseactivity给一个空方法，需要的就去实现

### ISSUE THREAD

**Issue by shenzhen-arrom** [Quyunshuo/AndroidBaseFrameMVVM#20]
initRequestData可以在baseactivity给一个空方法，需要的就去实现

**Comment by Quyunshuo** [comment]
> initRequestData可以在baseactivity给一个空方法，需要的就去实现

我的想法是强制实现，因为我在工作中，有些人是不看基类的，你默认实现了抽象行为，在继承时不会强制实现，而一些人自己又写了一些 `initData()` 的方法，所以我才没有提供默认实现，而是强制子类去实现

**Comment by Quyunshuo** [comment]
这个东西可以根据团队情况调整的，毕竟每个人的想法不一定一样，只要是为了代码质量提升就是可行的想法
