### ISSUE TITLE
buildSrc

### ISSUE THREAD

**Issue by zs18340282344** [Quyunshuo/AndroidBaseFrameMVVM#26]
这个包文件夹是怎么建出来的

**Comment by Quyunshuo** [comment]
> 这个包文件夹是怎么建出来的

手动创建的

**Comment by zs18340282344** [comment]
是新建一个mdule吗我在Androidstadio里没有找到这个新建的地方呢，因为我看你的工程这个文件夹还带着一个gradle.kts

**Comment by Quyunshuo** [comment]
> 是新建一个mdule吗我在Androidstadio里没有找到这个新建的地方呢，因为我看你的工程这个文件夹还带着一个gradle.kts

直接创建出这个文件夹，然后构建，as 会识别，自己再添加一些必要文件

**Comment by zs18340282344** [comment]
base_module这个是怎么创建的

**Comment by zs18340282344** [comment]
我手动创建报错Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:

**Comment by Quyunshuo** [comment]
> 我手动创建报错Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
base_module 就是正常创建的 module，在根目录下右击 new -> module
