### ISSUE TITLE
哥！从头到尾写个页面（假设登录带网络请求） 瞅瞅呗，拉下代码来 不太好跟着看

### ISSUE THREAD

**Issue by piratesHuo** [Quyunshuo/AndroidBaseFrameMVVM#28]
哥！从头到尾写个页面（假设登录带网络请求） 瞅瞅呗，拉下代码来 不太好跟着看

**Comment by Quyunshuo** [comment]
有一个比较早的 demo，你可以看着参考下， [WanAndroidMVVM](https://github.com/Quyunshuo/WanAndroidMVVM)。
另外这个项目我已经很久没有维护了，仅供参考学习哈
