### ISSUE TITLE
build.gradle: impor

### ISSUE THREAD

**Issue by Hell-And** [Quyunshuo/AndroidBaseFrameMVVM#4]
build.gradle里面的import关键字是什么语法，一直报错``

>
![KC6LB0 V~({JE3S4MHHEZTG](https://user-images.githubusercontent.com/24486325/105157442-eeac3180-5b47-11eb-9392-adecb59aba58.png)
![KC6LB0 V~({JE3S4MHHEZTG](https://user-images.githubusercontent.com/24486325/105157527-0683b580-5b48-11eb-8fa5-80674167fa44.png)

**Comment by Quyunshuo** [comment]
导包 意思是导入该包下的文件，这个包是buildSrc包下的，你看下是不是改动了包名
