### ISSUE TITLE
基类通过反射获取ViewBinding和ViewModel会不会影响性能？

### ISSUE THREAD

**Issue by panyy** [Quyunshuo/AndroidBaseFrameMVVM#5]
基类通过反射获取ViewBinding和ViewModel会不会影响性能？

**Comment by Quyunshuo** [comment]
反射肯定是比普通调用要慢，但是不至影响性能，虽然耗时一些，但是没那么严重，如果不能接受反射初始化也可以在基类通过抽象方法让子类实现初始化，这样的话就需要每次新建页面的时候去手动实现初始化方法，这个可以视个人意愿而定。我在项目里一直使用的反射，这种反射不会太耗时的。
