### ISSUE TITLE
Dispatchers.IO异常

### ISSUE THREAD

**Issue by chenmingyin** [Quyunshuo/AndroidBaseFrameMVVM#6]
你好，我刚才在运行代码时，ViewModel中的请求方法里面viewModelScope.launch(Dispatchers.IO)会导致异常java.lang.IllegalStateException: Cannot invoke setValue on a background thread。
原因是catch中的isLoading.value = false不能使用setValue。
如果换成viewModelScope.launch(Dispatchers.Main)就没有问题了，请问是什么原因呢？

**Comment by chenmingyin** [comment]
这样修改可以吗

**Comment by Quyunshuo** [comment]
>  先说为什么：

报错是因为在非主线程中不能调用setValue
> 分析：

首先你这个逻辑是在IO线程模式中执行的，属于非主线程，而isLoading是一个`LiveData`，`LiveData`有两种设置值的方式
```
void setValue(T value)
void postValue(T value)
```
`setValue()`是必须要在主线程中调用，但是你是在IO模式中调用的，所以会出现问题，而`postValue()`是可以在非主线程中调用。

> 解决办法：

使用`postValue()`进行设置值
